-- -------------------------<ORDERS>------------------------
--
-- INSERT INTO orders (user_id, product_number, user_email, user_details, order_number, price, quantity, total_price_order)
-- VALUES (1, 1234, 'john.doe@example.com', 'John Doe', 1001, 29.99, 2, 59.98);
-- INSERT INTO orders (user_id, product_number, user_email, user_details, order_number, price, quantity, total_price_order)
-- VALUES (2, 5678, 'jane.smith@example.com', 'Jane Smith', 1002, 49.99, 1, 49.99);
-- INSERT INTO orders (user_id, product_number, user_email, user_details, order_number, price, quantity, total_price_order)
-- VALUES (3, 9876, 'bob.jones@example.com', 'Bob Jones', 1003, 19.99, 3, 59.97);
--
-- --------------------------<INVOICES>---------------------------------------
--
-- INSERT INTO invoices (invoice_id, product_number, product_name, total_price, vat_21_product_price, vat_9_product_price, net_price_without_vat, vat_rate, vat_amount, user_id, user_address, product_warranty, warranty_in_months, date_of_purchase, product_type)
-- VALUES ('INV-001', 1234, 'Heggeschaar', 80.0, 16.8, 0.0, 63.2, 21.0, 13.29, 1, '123 Main St', true, 12, '2024-03-04', 'TUINMACHINE');
-- INSERT INTO invoices (invoice_id, product_number, product_name, total_price, vat_21_product_price, vat_9_product_price, net_price_without_vat, vat_rate, vat_amount, user_id, user_address, product_warranty, warranty_in_months, date_of_purchase, product_type)
-- VALUES ('INV-002', 5678, 'Bitset', 50.0, 10.5, 0.0, 39.5, 21.0, 8.29, 2, '456 Oak St', false, 0, '2024-03-05', 'BITSETS');
-- INSERT INTO invoices (invoice_id, product_number, product_name, total_price, vat_21_product_price, vat_9_product_price, net_price_without_vat, vat_rate, vat_amount, user_id, user_address, product_warranty, warranty_in_months, date_of_purchase, product_type)
-- VALUES ('INV-001', 1234, 'Heggeschaar', 80.0, 16.8, 0.0, 63.2, 21.0, 13.29, 1, '123 Main St', true, 12, '2024-03-04', 'TUINMACHINE');
--
-- -------------------------<WARRANTIES>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- INSERT INTO warranties (product_name, warranty_start, warranty_ends)
-- VALUES ('Heggeschaar', '2024-03-04', '2026-03-04');
-- INSERT INTO warranties (product_name)
-- VALUES ('Bitset');
-- INSERT INTO warranties (product_name, warranty_start, warranty_ends)
-- VALUES ('Schuurmachine', '2024-03-06', '2026-03-06');
--
-- -------------------------<PRODUCTS>----------------------------------------------
-- INSERT INTO products (brand_name, product_name, product_number, price, type_of_machine, product_warranty, warranty_in_months)
-- VALUES ('Metabo', 'Heggeschaar', 123, 79.99, 'TUINMACHINE', false, 0);
-- INSERT INTO products (brand_name, product_name, product_number, price, type_of_machine, product_warranty, warranty_in_months)
-- VALUES ('Metabo', 'Boormachine', 456, 149.99, 'BOORMACHINE', true, 24);
-- INSERT INTO products (brand_name, product_name, price, type_of_machine, product_warranty, warranty_in_months)
-- VALUES ('Metabo', 'Bitset', 29.99, 'BITSETS', false, 0);
--
-- --------------------------<STOCKCLASS>------------------------------------------------------------------------------------------------------------
--
--
--
--
--
--
--
--
--
--
--
--
-- -----------------------<USERS>-----------------------------------------